apiVersion: v1
kind: Service
metadata:
  name: redis-proxy
  namespace: sentry
  labels:
    app: redis-proxy
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  selector:
    k8s-app: redis-proxy
